# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy To Server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Start containers
      run: sudo docker-compose -f "docker-compose.yml" up -d --build
    - name: Running containers
      run: sudo docker ps
      
#     - name: Stop containers
#       if: always()
#       run: docker-compose -f "docker-compose.yml" down
